# rule identifiers to exclude from running
disabled_rules:
- colon
- identifier_name
- force_cast
- force_try
- control_statement
- type_body_length
- cyclomatic_complexity
- syntactic_sugar
- function_body_length
- shorthand_operator
- type_name

- multiple_closures_with_trailing_closure # 複数のクロージャーの場合でも、trailing closureを利用したいため
- empty_enum_arguments # enumの引数を省略したいため

# opt-inルールの中で無効にするルール
- conditional_returns_on_newline # ガード文などは簡潔に一行で記述したいため
- discouraged_optional_collection # PHImageManagerの既存仕様のため
- explicit_enum_raw_value # 暗黙的なraw値で問題ないため
- explicit_type_interface # 型推論を利用したいため
- fatal_error_message # メッセージは不要なため
- file_header # ヘッダには特に決まりがないため
- lower_acl_than_parent # 対応不可のため
- no_extension_access_modifier # extension_access_modifierを優先するため
- no_grouping_extension # グルーピングにextensionを利用したいため
- strict_fileprivate # fileprivateを利用したいため
#- switch_case_on_newline # caseと同じ行に記述したいため
- trailing_closure # RxSwiftのOnNextでwarningが出るため

# Lint対象から除外するパス
excluded:
- Carthage
- Pods
- build
- docs
- BwFrameworkTests

# rule identifiers to opt in
opt_in_rules:
  - closure_spacing


# special configuration for rules 
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false

function_parameter_count:
  warning: 6
  error: 8

function_body_length:
  warning: 40
  error: 100

file_length:
  warning: 600
  error: 1000

large_tuple:
  warning: 2
  error: 3

line_length:
  warning: 400 
  error: 700
  ignores_urls: false
  ignores_function_declarations: false
  ignores_comments: false

nesting:
    type_level: 3

large_tuple:
  error: 5
